/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;


public class KlientiMainForm extends javax.swing.JFrame {

    /**
     * Creates new form KlientiMainForm
     */
    public KlientiMainForm() {
        initComponents();
        setTitle("Klienti - Main Form");
        singOutIconPosition();

        //setFullScreen();//KJO
        setFormInMiddle();//KJO
    }

    private void singOutIconPosition() {
        logOut_KlientiBtn.setHorizontalTextPosition(SwingConstants.LEFT);
        logOut_KlientiBtn.setIconTextGap(5);

    }

//    //KJO
//    private void setFullScreen() {
//        Toolkit tk = Toolkit.getDefaultToolkit();
//        int xsize = (int) tk.getScreenSize().getWidth();
//        int ysize = (int) tk.getScreenSize().getHeight();
//        this.setSize(xsize, ysize);
//
//    }

    //KJO
    private void setFormInMiddle() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        background_panel_klienti = new javax.swing.JPanel();
        menaxho_PorositeBtn = new javax.swing.JButton();
        regjistro_biznesinBtn = new javax.swing.JButton();
        background_upper_klienti = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        emriKlientit = new javax.swing.JLabel();
        kohaKyqjes = new javax.swing.JLabel();
        emriKlientitJlabel = new javax.swing.JLabel();
        kohaKyqjesField = new javax.swing.JLabel();
        logOut_KlientiBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1205, 585));
        setResizable(false);

        desktopPane.setMinimumSize(new java.awt.Dimension(1205, 594));
        desktopPane.setVerifyInputWhenFocusTarget(false);

        background_panel_klienti.setBackground(new java.awt.Color(255, 255, 255));
        background_panel_klienti.setForeground(new java.awt.Color(255, 255, 255));
        background_panel_klienti.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        background_panel_klienti.setMinimumSize(new java.awt.Dimension(1205, 600));
        background_panel_klienti.setName(""); // NOI18N
        background_panel_klienti.setPreferredSize(new java.awt.Dimension(1205, 600));

        menaxho_PorositeBtn.setBackground(new java.awt.Color(204, 204, 255));
        menaxho_PorositeBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        menaxho_PorositeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/menaxhoPorosite_vectorized.png"))); // NOI18N
        menaxho_PorositeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menaxho_PorositeBtnMouseClicked(evt);
            }
        });
        menaxho_PorositeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menaxho_PorositeBtnActionPerformed(evt);
            }
        });

        regjistro_biznesinBtn.setBackground(new java.awt.Color(204, 204, 255));
        regjistro_biznesinBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        regjistro_biznesinBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/menaxhoPorosite_vectorized.png"))); // NOI18N
        regjistro_biznesinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regjistro_biznesinBtnActionPerformed(evt);
            }
        });

        background_upper_klienti.setBackground(new java.awt.Color(255, 255, 255));
        background_upper_klienti.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        background_upper_klienti.setMinimumSize(new java.awt.Dimension(1205, 151));
        background_upper_klienti.setPreferredSize(new java.awt.Dimension(1205, 151));

        jSeparator1.setBackground(new java.awt.Color(17, 17, 17));
        jSeparator1.setForeground(new java.awt.Color(17, 17, 17));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setOpaque(true);

        jSeparator2.setBackground(new java.awt.Color(17, 17, 17));
        jSeparator2.setForeground(new java.awt.Color(17, 17, 17));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setOpaque(true);

        emriKlientit.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        emriKlientit.setForeground(new java.awt.Color(204, 153, 255));
        emriKlientit.setText("Emri i klientit:");

        kohaKyqjes.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        kohaKyqjes.setForeground(new java.awt.Color(204, 153, 255));
        kohaKyqjes.setText("Koha e kyqjes:");

        emriKlientitJlabel.setFont(new java.awt.Font("SansSerif", 2, 13)); // NOI18N

        kohaKyqjesField.setFont(new java.awt.Font("SansSerif", 2, 13)); // NOI18N

        logOut_KlientiBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        logOut_KlientiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/icons8-export-48.png"))); // NOI18N
        logOut_KlientiBtn.setText("LOG OUT");
        logOut_KlientiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_KlientiBtnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(5);
        jTextArea1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 36)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 153, 255));
        jTextArea1.setText("      BPDS");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea3.setColumns(5);
        jTextArea3.setFont(new java.awt.Font("Leelawadee UI Semilight", 3, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(204, 153, 255));
        jTextArea3.setText("       BEAUTY PRODUCTS\n       DISTRIBUTION SYSTEM ");
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea2.setColumns(4);
        jTextArea2.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 28)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(204, 153, 255));
        jTextArea2.setText("         \n            CLIENT\n        DASHBOARD  ");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout background_upper_klientiLayout = new javax.swing.GroupLayout(background_upper_klienti);
        background_upper_klienti.setLayout(background_upper_klientiLayout);
        background_upper_klientiLayout.setHorizontalGroup(
            background_upper_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_upper_klientiLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(background_upper_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(background_upper_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_upper_klientiLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(kohaKyqjesField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addGroup(background_upper_klientiLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(background_upper_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background_upper_klientiLayout.createSequentialGroup()
                                .addComponent(emriKlientit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emriKlientitJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kohaKyqjes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOut_KlientiBtn)
                        .addContainerGap())))
        );
        background_upper_klientiLayout.setVerticalGroup(
            background_upper_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_upper_klientiLayout.createSequentialGroup()
                .addGroup(background_upper_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_upper_klientiLayout.createSequentialGroup()
                        .addGroup(background_upper_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background_upper_klientiLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(emriKlientitJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(background_upper_klientiLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(background_upper_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(logOut_KlientiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(background_upper_klientiLayout.createSequentialGroup()
                                        .addComponent(emriKlientit)
                                        .addGap(18, 18, 18)
                                        .addComponent(kohaKyqjes)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kohaKyqjesField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background_upper_klientiLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background_upper_klientiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(background_upper_klientiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background_upper_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_upper_klientiLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(background_upper_klientiLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(14, 14, 14))))
        );

        jTextArea4.setColumns(5);
        jTextArea4.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        jTextArea4.setRows(1);
        jTextArea4.setText("  MANAGE BUSINESSES ");
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea5.setColumns(5);
        jTextArea5.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        jTextArea5.setRows(1);
        jTextArea5.setText("         MANAGE ORDERS");
        jScrollPane5.setViewportView(jTextArea5);
        jTextArea5.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout background_panel_klientiLayout = new javax.swing.GroupLayout(background_panel_klienti);
        background_panel_klienti.setLayout(background_panel_klientiLayout);
        background_panel_klientiLayout.setHorizontalGroup(
            background_panel_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_panel_klientiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background_upper_klienti, javax.swing.GroupLayout.DEFAULT_SIZE, 1298, Short.MAX_VALUE)
                .addGap(60, 60, 60))
            .addGroup(background_panel_klientiLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(regjistro_biznesinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(menaxho_PorositeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(background_panel_klientiLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        background_panel_klientiLayout.setVerticalGroup(
            background_panel_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background_panel_klientiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(background_upper_klienti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(background_panel_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menaxho_PorositeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regjistro_biznesinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background_panel_klientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        desktopPane.add(background_panel_klienti);
        background_panel_klienti.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regjistro_biznesinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regjistro_biznesinBtnActionPerformed
        BiznesiInternalForm bif = new BiznesiInternalForm();
        desktopPane.add(bif);
        bif.show();
        bif.setFocusable(true);
    }//GEN-LAST:event_regjistro_biznesinBtnActionPerformed

    private void logOut_KlientiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_KlientiBtnActionPerformed
        try {
            int choice;
            choice = JOptionPane.showConfirmDialog(null, "Deshironi te dilni?", "Logout", JOptionPane.INFORMATION_MESSAGE);
            if (choice == JOptionPane.YES_OPTION) {
                this.dispose();
                LogIn a = new LogIn();
                a.setVisible(true);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_logOut_KlientiBtnActionPerformed

    private void menaxho_PorositeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menaxho_PorositeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menaxho_PorositeBtnActionPerformed

    private void menaxho_PorositeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menaxho_PorositeBtnMouseClicked
        PorosiaInternalForm ppf = new PorosiaInternalForm();
        desktopPane.add(ppf);
        ppf.show();
        ppf.setFocusable(true);
    }//GEN-LAST:event_menaxho_PorositeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlientiMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlientiMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlientiMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlientiMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlientiMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background_panel_klienti;
    private javax.swing.JPanel background_upper_klienti;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel emriKlientit;
    public static javax.swing.JLabel emriKlientitJlabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    public static javax.swing.JLabel kohaKyqjes;
    public static javax.swing.JLabel kohaKyqjesField;
    private javax.swing.JButton logOut_KlientiBtn;
    private javax.swing.JButton menaxho_PorositeBtn;
    private javax.swing.JButton regjistro_biznesinBtn;
    // End of variables declaration//GEN-END:variables

}
