/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import BLL.Punetori;
import BLL.Users;
import DAL.PunetoriInterface;
import DAL.PunetoriRepository;
import DAL.UsersInterface;
import DAL.UsersRepository;
import Exceptions.PunetoriException;
import Exceptions.UsersException;
import java.awt.Component;
import java.awt.event.MouseMotionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;


public class ProfiliImMenaxher extends javax.swing.JInternalFrame {

    PunetoriInterface pri = new PunetoriRepository();
    UsersInterface uie = new UsersRepository();

    /**
     * Creates new form ProfiliImMenaxher
     */
    public ProfiliImMenaxher() {
        try {
            initComponents();
            idTextField.setEditable(false);
            idField.setEditable(false);
            setFormFullScren();
            disableProfiliImFormDrag();
            setPunetoriData();
        } catch (UsersException ex) {

        }

    }

    private void setFormFullScren() {
        int xsize = (int) gui.view.PunetoriMenaxherMainForm.desktopPane.getWidth();
        int ysize = (int) gui.view.PunetoriMenaxherMainForm.desktopPane.getHeight();
        this.setSize(xsize, ysize);
    }

    private void disableProfiliImFormDrag() {
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        Component northPane = ui.getNorthPane();
        MouseMotionListener[] motionListeners = (MouseMotionListener[]) northPane.getListeners(MouseMotionListener.class);

        for (MouseMotionListener listener : motionListeners) {
            northPane.removeMouseMotionListener(listener);
        }
    }

    private void setPunetoriData() throws UsersException {
        String punetoriId = (PunetoriMenaxherMainForm.idPunetoritSave + "");
        String userId = (PunetoriMenaxherMainForm.u);

        try {
            List<Punetori> listaPunetoreve = pri.findAll();
            List<Users> listaUserave = uie.findAll();
            Punetori p;
            for (int i = 0; i < listaPunetoreve.size(); i++) {
                if (listaPunetoreve.get(i).getPId().equals(Integer.parseInt(punetoriId))) {
                    p = listaPunetoreve.get(i);
                    idTextField.setText(punetoriId);
                    emriTextField.setText(p.getEmri());
                    MbiemriTextField.setText(p.getMbiemri());
                    MoshaTextField.setText(p.getMosha() + "");
                    AdresaTextField.setText(p.getAdresa());
                    gjiniaComboProfile.setSelectedItem(p.getGjinia());

                }

            }
            Users usr;
            for (int i = 0; i < listaUserave.size(); i++) {
                if (listaUserave.get(i).getUId().equals(Integer.parseInt(userId))) {
                    usr = listaUserave.get(i);
                    idField.setText(userId);
                    usernameField.setText(usr.getUIdlog());
                    jPasswordField.setText(usr.getUPassword());
                }
            }
        } catch (PunetoriException ex) {

        }
    }

    private static boolean kaVetemShkronja(String input) {
        for (int i = 0; i < input.length(); ++i) {
            if (!Character.isLetter(input.charAt(i))) {
                return false;
            }
        }
        return true;
    }

    public boolean ekzistonLlogaria() {
        try {
            String user_id = usernameField.getText().trim();
            List<Users> lista = uie.findAll();
            for (int i = 0; i < lista.size(); i++) {
                if (lista.get(i).getUIdlog().equals(user_id)) {
                    JOptionPane.showMessageDialog(this, "CPDS: Kjo llogari është e regjistruar në kompani.");
                    return true;
                }
            }

        } catch (UsersException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MyProfileMenaxheriBackground = new javax.swing.JPanel();
        MyProfileMenaxheriUpperBackground = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TeDhenatEPunetoritJlabel = new javax.swing.JLabel();
        teDhenatPerKyqjeJlabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        idTextField = new javax.swing.JTextField();
        emriTextField = new javax.swing.JTextField();
        MbiemriTextField = new javax.swing.JTextField();
        MoshaTextField = new javax.swing.JTextField();
        AdresaTextField = new javax.swing.JTextField();
        gjiniaComboProfile = new javax.swing.JComboBox<String>();
        idJlabel = new javax.swing.JLabel();
        emriJlabel = new javax.swing.JLabel();
        mbiemriJlabel = new javax.swing.JLabel();
        moshaJlabel = new javax.swing.JLabel();
        adresaJlabel = new javax.swing.JLabel();
        gjiniaJlabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameJlabel = new javax.swing.JLabel();
        passwordJlabel = new javax.swing.JLabel();
        ResetBtn = new javax.swing.JButton();
        RuajBtn = new javax.swing.JButton();
        showRaddio = new javax.swing.JRadioButton();
        HideRadio = new javax.swing.JRadioButton();
        RuajBtn2 = new javax.swing.JButton();
        ResetBtn2 = new javax.swing.JButton();
        usernameJlabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(2000, 1200));

        MyProfileMenaxheriBackground.setBackground(new java.awt.Color(255, 255, 255));
        MyProfileMenaxheriBackground.setMaximumSize(new java.awt.Dimension(2000, 1100));

        MyProfileMenaxheriUpperBackground.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(5);
        jTextArea1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        jTextArea1.setRows(1);
        jTextArea1.setText("            PROFILI IM ");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout MyProfileMenaxheriUpperBackgroundLayout = new javax.swing.GroupLayout(MyProfileMenaxheriUpperBackground);
        MyProfileMenaxheriUpperBackground.setLayout(MyProfileMenaxheriUpperBackgroundLayout);
        MyProfileMenaxheriUpperBackgroundLayout.setHorizontalGroup(
            MyProfileMenaxheriUpperBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyProfileMenaxheriUpperBackgroundLayout.createSequentialGroup()
                .addGap(505, 505, 505)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MyProfileMenaxheriUpperBackgroundLayout.setVerticalGroup(
            MyProfileMenaxheriUpperBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyProfileMenaxheriUpperBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        TeDhenatEPunetoritJlabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        TeDhenatEPunetoritJlabel.setText("Të dhënat e punëtorit:");

        teDhenatPerKyqjeJlabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        teDhenatPerKyqjeJlabel.setText("Të dhënat për kyqje:");

        jSeparator1.setBackground(new java.awt.Color(45, 45, 45));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setOpaque(true);

        idTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        idTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        emriTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        emriTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        MbiemriTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        MbiemriTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MbiemriTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbiemriTextFieldActionPerformed(evt);
            }
        });

        MoshaTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        MoshaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        AdresaTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AdresaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gjiniaComboProfile.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mashkull", "Femer" }));

        idJlabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        idJlabel.setText("id:");

        emriJlabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        emriJlabel.setText("emri:");

        mbiemriJlabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        mbiemriJlabel.setText("mbiemri:");

        moshaJlabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        moshaJlabel.setText("mosha:");

        adresaJlabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        adresaJlabel.setText("adresa:");

        gjiniaJlabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        gjiniaJlabel.setText("gjinia:");

        usernameField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        usernameJlabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        usernameJlabel.setText("username:");

        passwordJlabel.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        passwordJlabel.setText("password:");

        ResetBtn.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        ResetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/reset_profile.png"))); // NOI18N
        ResetBtn.setText("RESET");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        RuajBtn.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        RuajBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/save_profile.png"))); // NOI18N
        RuajBtn.setText("RUAJ");
        RuajBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuajBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(showRaddio);
        showRaddio.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        showRaddio.setText("SHOW");
        showRaddio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRaddioActionPerformed(evt);
            }
        });

        buttonGroup1.add(HideRadio);
        HideRadio.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        HideRadio.setText("HIDE");
        HideRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HideRadioActionPerformed(evt);
            }
        });

        RuajBtn2.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        RuajBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/save_profile.png"))); // NOI18N
        RuajBtn2.setText("RUAJ");
        RuajBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuajBtn2ActionPerformed(evt);
            }
        });

        ResetBtn2.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        ResetBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/reset_profile.png"))); // NOI18N
        ResetBtn2.setText("RESET");
        ResetBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtn2ActionPerformed(evt);
            }
        });

        usernameJlabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        usernameJlabel1.setText("username id:");

        idField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        idField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout MyProfileMenaxheriBackgroundLayout = new javax.swing.GroupLayout(MyProfileMenaxheriBackground);
        MyProfileMenaxheriBackground.setLayout(MyProfileMenaxheriBackgroundLayout);
        MyProfileMenaxheriBackgroundLayout.setHorizontalGroup(
            MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyProfileMenaxheriUpperBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                        .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                                .addContainerGap(137, Short.MAX_VALUE)
                                .addComponent(RuajBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123))
                            .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idJlabel)
                                    .addComponent(emriJlabel)
                                    .addComponent(mbiemriJlabel)
                                    .addComponent(moshaJlabel)
                                    .addComponent(adresaJlabel)
                                    .addComponent(gjiniaJlabel))
                                .addGap(18, 18, 18)
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MbiemriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MoshaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AdresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gjiniaComboProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(TeDhenatEPunetoritJlabel)))
                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(RuajBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernameJlabel1)
                            .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameJlabel)
                                    .addComponent(passwordJlabel))
                                .addGap(11, 11, 11)))
                        .addGap(18, 18, 18)
                        .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(teDhenatPerKyqjeJlabel))
                                .addGap(184, 184, 184))
                            .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                                        .addComponent(ResetBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 36, Short.MAX_VALUE))
                                    .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                                        .addComponent(showRaddio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(HideRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        MyProfileMenaxheriBackgroundLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AdresaTextField, MbiemriTextField, MoshaTextField, emriTextField, gjiniaComboProfile, idTextField});

        MyProfileMenaxheriBackgroundLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ResetBtn, RuajBtn});

        MyProfileMenaxheriBackgroundLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordField, usernameField});

        MyProfileMenaxheriBackgroundLayout.setVerticalGroup(
            MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(MyProfileMenaxheriUpperBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeDhenatEPunetoritJlabel)
                            .addComponent(teDhenatPerKyqjeJlabel))
                        .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idJlabel))
                                .addGap(30, 30, 30)
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emriJlabel))
                                .addGap(30, 30, 30)
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MbiemriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mbiemriJlabel))
                                .addGap(30, 30, 30)
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MoshaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(moshaJlabel))
                                .addGap(30, 30, 30)
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AdresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adresaJlabel))
                                .addGap(30, 30, 30)
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gjiniaComboProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gjiniaJlabel))
                                .addGap(66, 66, 66)
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RuajBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameJlabel1)
                                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)
                                    .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameJlabel)
                                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(showRaddio)
                                        .addComponent(HideRadio)
                                        .addComponent(passwordJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(226, 226, 226)))))
                    .addGroup(MyProfileMenaxheriBackgroundLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MyProfileMenaxheriBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RuajBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ResetBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        MyProfileMenaxheriBackgroundLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AdresaTextField, MbiemriTextField, MoshaTextField, emriTextField, gjiniaComboProfile, idTextField});

        MyProfileMenaxheriBackgroundLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ResetBtn, RuajBtn});

        MyProfileMenaxheriBackgroundLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {idField, jPasswordField, usernameField});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyProfileMenaxheriBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyProfileMenaxheriBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MbiemriTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbiemriTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MbiemriTextFieldActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void showRaddioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRaddioActionPerformed
        jPasswordField.setEchoChar((char) 0);
    }//GEN-LAST:event_showRaddioActionPerformed

    private void HideRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HideRadioActionPerformed
        jPasswordField.setEchoChar('*');
    }//GEN-LAST:event_HideRadioActionPerformed
    private void clearFields() {
        idTextField.setText("");
        emriTextField.setText("");
        MbiemriTextField.setText("");
        MoshaTextField.setText("");
        AdresaTextField.setText("");
        idField.setText("");
        usernameField.setText("");
        jPasswordField.setText("");

    }

    private char ktheGjinine() {
        char gender;
        String gjinia = (String) gjiniaComboProfile.getSelectedItem();
        if (gjinia.equals("Mashkull")) {
            gender = 'M';
        } else {
            gender = 'F';
        }
        return gender;
    }


    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        try {
            clearFields();
            setPunetoriData();
        } catch (UsersException ex) {

        }

    }//GEN-LAST:event_ResetBtnActionPerformed

    private void RuajBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuajBtnActionPerformed
        try {
            List<Punetori> listaPunetoreve = pri.findAll();
            Punetori p = null;
            for (int i = 0; i < listaPunetoreve.size(); i++) {
                if (listaPunetoreve.get(i).getPId().equals(Integer.parseInt(idTextField.getText()))) {
                    p = listaPunetoreve.get(i);
                }
            }

            String emriStandard = emriTextField.getText().replaceAll("\\s", "");
            String mbiemriStandard = MbiemriTextField.getText().replaceAll("\\s", "");
            String adresaStandard = AdresaTextField.getText();

            String emriModified = emriStandard.substring(0, 1).toUpperCase() + emriStandard.substring(1);
            String mbiemriModified = mbiemriStandard.substring(0, 1).toUpperCase() + mbiemriStandard.substring(1);
            String adresaModified = adresaStandard.substring(0, 1).toUpperCase() + adresaStandard.substring(1);

            if (kaVetemShkronja(emriModified) && kaVetemShkronja(mbiemriModified)) {
                p.setEmri(emriModified);
                p.setMbiemri(mbiemriModified);
                p.setAdresa(adresaModified);
                p.setGjinia(ktheGjinine());
            } else {
                JOptionPane.showMessageDialog(this, "CPDS: Keni shtypur karakter te pa lejueshem. Ju lutem mbushni hapsirat vetem me karaktere te lejuara.");
                clearFields();
                return;
            }
            try {
                Integer mosha = Integer.parseInt(MoshaTextField.getText().replaceAll("\\s", ""));
                if (mosha > 50 || mosha < 18) {
                    JOptionPane.showMessageDialog(this, "CPDS: Mosha e punetorit nuk munde te jete me e vogel "
                            + "se 18 vjeq dhe me e madhe se 50 vjeq.");
                    MoshaTextField.setText("");
                    return;

                } else {
                    p.setMosha(mosha);
                }
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "CPDS: Mosha e punetorit duhet te kete vlere numerike.");
                MoshaTextField.setText("");
                return;
            }
            try {
                Integer mosha = Integer.parseInt(MoshaTextField.getText().replaceAll("\\s", ""));
                Object[] ob = {"Po", "Jo"};
                int result = JOptionPane.showOptionDialog(this, "CPDS: A jeni i sigurtë qe dëshironi të ndryshoni të dhenat e juaja personale?"
                        + "\n\nEmri: " + emriModified + "\nMbiemri: " + mbiemriModified + "\nMosha: " + mosha + "\nAdresa: " + adresaModified + "\nGjinia: " + ktheGjinine(), "Kujdes!", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                if (result == 0) {
                    gui.view.PunetoriMenaxherMainForm.emriPunetoritJlabel.setText(emriModified + " " + mbiemriModified);
                    pri.edit(p);

                    idTextField.setText((p.getPId() + ""));
                    emriTextField.setText(p.getEmri());
                    MbiemriTextField.setText(p.getMbiemri());
                    MoshaTextField.setText(p.getMosha() + "");
                    AdresaTextField.setText(p.getAdresa());
                    gjiniaComboProfile.setSelectedItem(p.getGjinia());

                    idField.setText(PunetoriMenaxherMainForm.u);
                    usernameField.setText(PunetoriMenaxherMainForm.usernameId);
                    jPasswordField.setText(PunetoriMenaxherMainForm.passwordUsr);
                }
            } catch (PunetoriException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        } catch (PunetoriException ex) {

        }
    }//GEN-LAST:event_RuajBtnActionPerformed


    private void ResetBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtn2ActionPerformed
        try {
            clearFields();
            setPunetoriData();
        } catch (UsersException ex) {

        }
    }//GEN-LAST:event_ResetBtn2ActionPerformed

    private void RuajBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuajBtn2ActionPerformed
        try {
            List<Users> listaUserave = uie.findAll();

            Users p = null;
            for (int i = 0; i < listaUserave.size(); i++) {
                if (listaUserave.get(i).getUId().equals(Integer.parseInt(idField.getText()))) {
                    p = listaUserave.get(i);
                }
            }
            String idUserit = usernameField.getText().replaceAll("\\s", "");
            if (kaVetemShkronja(idUserit)) {
                if (ekzistonLlogaria()) {
                    return;
                }
                try {
                    if (idUserit != null) {
                        p.setUIdlog(idUserit);
                    }
                } catch (Exception ex) {

                }
                p.setUPassword(jPasswordField.getText());
            } else {
                JOptionPane.showMessageDialog(this, "CPDS: Keni shtypur karakter te pa lejueshem ne hapsiren për username.");
                return;
            }
            Object[] ob = {"Po", "Jo"};
            int result = JOptionPane.showOptionDialog(this, "CPDS: A jeni i sigurtë qe dëshironi të ndryshoni të dhenat për kyqje?"
                    + "\n\nUsername: " + idUserit + "\nPassword: " + jPasswordField.getText(), "Kujdes!", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
            if (result == 0) {
                uie.edit(p);

            }
        } catch (UsersException ex) {

        }
    }//GEN-LAST:event_RuajBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdresaTextField;
    private javax.swing.JRadioButton HideRadio;
    private javax.swing.JTextField MbiemriTextField;
    private javax.swing.JTextField MoshaTextField;
    private javax.swing.JPanel MyProfileMenaxheriBackground;
    private javax.swing.JPanel MyProfileMenaxheriUpperBackground;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton ResetBtn2;
    private javax.swing.JButton RuajBtn;
    private javax.swing.JButton RuajBtn2;
    private javax.swing.JLabel TeDhenatEPunetoritJlabel;
    private javax.swing.JLabel adresaJlabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel emriJlabel;
    private javax.swing.JTextField emriTextField;
    private static javax.swing.JComboBox<String> gjiniaComboProfile;
    private javax.swing.JLabel gjiniaJlabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idJlabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel mbiemriJlabel;
    private javax.swing.JLabel moshaJlabel;
    private javax.swing.JLabel passwordJlabel;
    private javax.swing.JRadioButton showRaddio;
    private javax.swing.JLabel teDhenatPerKyqjeJlabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameJlabel;
    private javax.swing.JLabel usernameJlabel1;
    // End of variables declaration//GEN-END:variables
}
